# Generated by Django 5.1.6 on 2025-04-01 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_Estudiantes', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=10)),
                ('fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id_preguntas', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=50)),
                ('respuesta_correcta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id_profesores', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=10)),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Simulacro',
            fields=[
                ('id_Simulacro', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=15)),
                ('fecha_registro', models.DateField()),
                ('tiempo_limite', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Puntaje_decimal', models.CharField(max_length=45)),
                ('Fecha_realizacion', models.DateField()),
                ('id_Estudiantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.estudiante')),
                ('id_Simulacro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.simulacro')),
            ],
        ),
    ]
